services:
  - type: web
    name: e-commerce-site
    env: node
    runtime: node
    repo: https://github.com/fredm23579/e-commerce-site
    branch: works
    buildCommand: npm install @vitejs/plugin-react && npm run render-build
    startCommand: node server/server.js
    staticPublishPath: client/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI 
        fromDatabase:
          name: mongodb-ecommerce-site
          property: connectionString
      - key: STRIPE_SECRET_KEY
        fromSecret: stripe_secret_key
      - key: REACT_APP_BACKEND_URL
        value: https://e-commerce-site-us2y.onrender.com
      - key: REACT_APP_API_URL
        value: https://e-commerce-site-us2y.onrender.com/graphql
    database:
      type: mongodb
      name: mongodb-ecommerce-site
version: "1"
